name: .NET

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@master

    - name: Build
      run: msbuild RedirectStdouts\RedirectStdouts.sln /p:Configuration=Release
    
    - uses: actions/upload-artifact@v2
      with:
        name: "exe"
        path: RedirectStdouts\bin\Release\RedirectStdouts.exe
